let val;

val =document.all.length;
val = document.getElementById('document-tittle').style.background= '#333';
val=document.getElementById("document-tittle").textContent='Hello World'

val=document.getElementById("document-tittle")

let list=document.querySelector("ol");
val=list;
let liItem=document.querySelector('ol');

liItem.appendChild(document.createTextNode('JavaScript'));

//document.querySelector('ol').appendChild(liItem);

//console.log(liItem);